// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sijkbahcrzepdmththon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpamtiYWhjcnplcGRtdGh0aG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODAyNjUsImV4cCI6MjA2ODA1NjI2NX0.4haZt0aeIzQ9RlRLr5KkFfr6g8Xv0-xklF7ejxt80Po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});